'use strict';

const CODES = Object.freeze({
  E_NOT_IMPLEMENTED: 'E_NOT_IMPLEMENTED',
  E_UNKNOWN_SUBCOMMAND: 'E_UNKNOWN_SUBCOMMAND',
  E_UNKNOWN_FLAG: 'E_UNKNOWN_FLAG',
  E_MISSING_ARG: 'E_MISSING_ARG',
  E_INVALID_JSON: 'E_INVALID_JSON',
  E_INVALID_YAML: 'E_INVALID_YAML',
  E_IO: 'E_IO',
  E_INVALID_CONTRACT: 'E_INVALID_CONTRACT',
  E_INVALID_PLAN: 'E_INVALID_PLAN',
  E_WORKTREE_CREATE: 'E_WORKTREE_CREATE',
  E_WORKTREE_REMOVE: 'E_WORKTREE_REMOVE',
  E_EXECUTOR: 'E_EXECUTOR',
  E_VERIFY: 'E_VERIFY',
  E_STATE: 'E_STATE',
  E_UNKNOWN_DISPATCHER: 'E_UNKNOWN_DISPATCHER',
  E_UNSUPPORTED_LANGUAGE: 'E_UNSUPPORTED_LANGUAGE',
  E_COVERAGE_UNAVAILABLE: 'E_COVERAGE_UNAVAILABLE',
  E_NULL_LESSON: 'E_NULL_LESSON',
  E_INVALID_LESSON: 'E_INVALID_LESSON',
  E_INVALID_SUPERSESSION: 'E_INVALID_SUPERSESSION',
  E_INDEX_DESYNC: 'E_INDEX_DESYNC',
  E_COURT_INPUT_VIOLATION: 'E_COURT_INPUT_VIOLATION',
  E_INVALID_VERDICT: 'E_INVALID_VERDICT',
  E_RESET_REFUSED: 'E_RESET_REFUSED',
  E_ABORT_REASON_REQUIRED: 'E_ABORT_REASON_REQUIRED',
  E_INVALID_TRACE_EVENT: 'E_INVALID_TRACE_EVENT',
  E_HOOK_BLOCKED: 'E_HOOK_BLOCKED',
  E_THEATRE_DRIFT_EXCEEDED: 'E_THEATRE_DRIFT_EXCEEDED',
  E_SHIP_PR_FAILED: 'E_SHIP_PR_FAILED',
  E_SHIP_APPROVAL_TOKEN_INVALID: 'E_SHIP_APPROVAL_TOKEN_INVALID',
  E_SHIP_REPLAY_FAILED: 'E_SHIP_REPLAY_FAILED',
  E_WHOLE_BRANCH_COURT_FAILED: 'E_WHOLE_BRANCH_COURT_FAILED',
  E_NO_ESCALATED_TASKS: 'E_NO_ESCALATED_TASKS',
  E_ESCALATION_TASK_NOT_FOUND: 'E_ESCALATION_TASK_NOT_FOUND'
});

function makeError(code, message, details) {
  const err = new Error(message);
  err.error = message;
  err.code = code;
  err.details = details === undefined ? null : details;
  return err;
}

function writeErrorAndExit(code, message, details) {
  const obj = { error: message, code: code, details: details === undefined ? null : details };
  process.stderr.write(JSON.stringify(obj) + '\n');
  process.exit(1);
}

module.exports = { CODES, makeError, writeErrorAndExit };
